# Generated by Django 5.0.3 on 2024-03-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=58.011485),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=56.238825),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
